version: '3'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
    environment:
      - PASSWORD_MANAGER_KEY=secretkey
    command: python password_manager.py
